spring.application.name=Internship_API_Gateway
server.port=8084

spring.main.web-application-type=reactive

management.endpoints.web.exposure.include=gateway,env,health
management.endpoint.gateway.enabled=true

logging.level.org.springframework.cloud.gateway=TRACE
